name: Update CSV

on:
    schedule:
      - cron:  '0 9 1 * *'
    workflow_dispatch:

permissions: read-all

jobs:
    update-data:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Harden runner
              uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40
              with:
                  disable-sudo: true
                  egress-policy: audit

            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

            - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
              with:
                python-version: ${{ matrix.python-version }}
                activate-environment: true
                cache-dependency-glob: |
                  **/pyproject.toml
                  **/uv.lock
    
            - run: uv sync

            - name: Run package
              run: maine_state_senator_data

            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
              with:
                commit_message: Updated legislator data
